name: "Main / Pull requests build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [ main ]
    push:
        branches:
            - main

jobs:
    pre-commit:
        name: Pre-commit check
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout git repository
                uses: actions/checkout@v4.1.6
            -   uses: actions/setup-java@v4.2.1
                with:
                    distribution: 'temurin'
                    java-version: '23'
            -   name: Pre-commit checks
                uses: pre-commit/action@v3.0.1
                with:
                    extra_args: --all-files
            -   name: pre-commit-c-lite
                uses: pre-commit-ci/lite-action@v1.1.0
                if: always()

    build:
        name: Build
        runs-on: ubuntu-latest
        needs: [pre-commit]
        strategy:
            fail-fast: true
            max-parallel: 1
        steps:
            -   uses: actions/checkout@v4.1.6
            -   name: Set up JDK 23
                uses: actions/setup-java@v4.2.1
                with:
                    distribution: 'temurin'
                    java-version: 23
                    architecture: x64
                    cache: 'maven'
            -   name: Compile project with Maven
                run: mvn --no-transfer-progress clean compile
    depcheck:
        name: OWAS Dependency Check
        runs-on: ubuntu-latest
        needs: [build]
        strategy:
            fail-fast: true
            max-parallel: 1
        steps:
            -   uses: actions/checkout@v4.1.6
            -   name: Run OWASP Dependency Check
                run: mvn org.owasp:dependency-check-maven:check -DnvdApiKey=${{ secrets.NVD_API_KEY }} -DfailBuildOnCVSS=7
            -   name: Upload Dependency Check report
                uses: actions/upload-artifact@master
                with:
                    name: Target artifact
                    path: ${{github.workspace}}/target
                if: always()
            -   name: Install dependencies
                run:
                if: always()
    test:
        name: Tests
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            -   name: Run JUnit Tests
                run: mvn install
                if: always()

    sonarqube:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    # Disabling shallow clones is recommended for improving the relevancy of reporting
                    fetch-depth: 0
            -   name: SonarQube Scan
                uses: SonarSource/sonarqube-scan-action@v5.2.0 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
