name: "Main / Pull requests build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [ main ]
    push:
        branches:
            - main

env:
  NVD_API_KEY: 5f2ac5de-2dfc-4760-a677-999c3898c8d7

jobs:
    pre-commit:
        name: Pre-commit check
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout git repository
                uses: actions/checkout@v4.1.6
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '23'
            -   name: Pre-commit checks
                uses: pre-commit/action@v3.0.1
            -   name: pre-commit-c-lite
                uses: pre-commit-ci/lite-action@v1.1.0
                if: always()
    build:
        runs-on: ubuntu-latest
        needs: [ pre-commit ]
        strategy:
            fail-fast: true
            max-parallel: 1
        steps:
            -   uses: actions/checkout@v4.1.6
            -   name: Set up JDK 23
                uses: actions/setup-java@v4.2.1
                with:
                    distribution: 'temurin'
                    java-version: 23
                    architecture: x64
                    cache: 'maven'
            -   name: Build with Maven
                run: mvn --no-transfer-progress verify
    dependency-check:
        name: Run OWASP Dependency Check
        runs-on: ubuntu-latest
        steps:
            - name: Check with Maven plugin
              run: mvn org.owasp:dependency-check-maven:check  
