name: Feature Branch Security Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - main
    paths:
      - 'pom.xml'
      - 'Dockerfile'
      - '.github/workflows/**'
      - 'src/**'

permissions:
  contents: read
  issues: write
  pull-requests: write
  security-events: write
  actions: read

jobs:
  security-scan:
    name: 🔍 Security Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout Feature Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 📦 Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: 🔍 Security Vulnerability Analysis
        id: dependabot-scan
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              // Try to get repository vulnerability alerts
              const { data: alerts } = await github.rest.dependabot.listAlertsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                sort: 'created',
                direction: 'desc'
              });
              
              console.log(`✅ Successfully accessed Dependabot alerts: Found ${alerts.length} open vulnerability alerts`);
              
              // Filter for medium+ severity vulnerabilities
              const mediumPlusVulns = alerts.filter(alert => {
                const severity = alert.security_vulnerability.severity.toLowerCase();
                return ['medium', 'high', 'critical'].includes(severity);
              });
              
              console.log(`Found ${mediumPlusVulns.length} medium+ severity vulnerabilities`);
              
              // Set outputs for next steps
              core.setOutput('total-vulns', alerts.length);
              core.setOutput('medium-plus-vulns', mediumPlusVulns.length);
              core.setOutput('vulnerabilities', JSON.stringify(mediumPlusVulns));
              core.setOutput('scan-method', 'dependabot-api');
              core.setOutput('scan-status', 'success');
              
              return mediumPlusVulns;
            } catch (error) {
              console.warn('⚠️ Dependabot API not accessible:', error.message);
              
              // Handle 403 errors (GitHub Advanced Security not enabled)
              if (error.status === 403) {
                console.log('📋 GitHub Advanced Security is required for Dependabot alerts API');
                console.log('💡 Alternative: Using Maven dependency check as fallback');
                
                // Set fallback outputs
                core.setOutput('total-vulns', 0);
                core.setOutput('medium-plus-vulns', 0);
                core.setOutput('vulnerabilities', JSON.stringify([]));
                core.setOutput('scan-method', 'fallback-required');
                core.setOutput('scan-status', 'limited');
                core.setOutput('error-reason', 'GitHub Advanced Security not enabled');
                
                return [];
              } else {
                // For other errors, fail the workflow
                                 core.setFailed(`Failed to fetch vulnerability alerts: ${error.message}`);
               }
             }

      - name: 🔧 Fallback Maven Security Check
        if: steps.dependabot-scan.outputs.scan-method == 'fallback-required'
        id: maven-security-check
        run: |
          echo "🔍 Running Maven OWASP Dependency Check as fallback..."
          
          # Check if OWASP dependency check plugin is configured
          if grep -q "org.owasp" pom.xml; then
            echo "✅ OWASP plugin found in pom.xml"
            mvn org.owasp:dependency-check-maven:check -DfailBuildOnCVSS=7 -DsuppressionFiles=config/dependency-check/project-suppression.xml || true
            
            # Check if report was generated
            if [ -f "target/dependency-check-report.html" ]; then
              echo "📊 Security report generated"
              echo "has-report=true" >> $GITHUB_OUTPUT
            else
              echo "⚠️ No security report generated"
              echo "has-report=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "⚠️ OWASP dependency check plugin not configured"
            echo "💡 Consider adding org.owasp:dependency-check-maven plugin to pom.xml"
            echo "has-report=false" >> $GITHUB_OUTPUT
          fi

      - name: 📊 Generate Vulnerability Report
        id: generate-report
        if: steps.dependabot-scan.outputs.medium-plus-vulns > 0 || steps.dependabot-scan.outputs.scan-method == 'fallback-required'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scanMethod = '${{ steps.dependabot-scan.outputs.scan-method }}';
            const scanStatus = '${{ steps.dependabot-scan.outputs.scan-status }}';
            
            let report = '';
            
            if (scanMethod === 'fallback-required') {
              // Generate report for fallback scenario
              report = '⚠️ **Security Scan Status Report**\n\n';
              report += '**⚠️ Limited Security Scanning Available**\n\n';
              report += '**Issue**: GitHub Advanced Security is not enabled for this repository.\n\n';
              report += '**What this means**:\n';
              report += '- Dependabot vulnerability alerts are not accessible\n';
              report += '- Advanced security scanning features are unavailable\n';
              report += '- Limited vulnerability detection capability\n\n';
              
              const hasReport = '${{ steps.maven-security-check.outputs.has-report }}' === 'true';
              if (hasReport) {
                report += '**✅ Fallback Scan Completed**:\n';
                report += '- Maven OWASP dependency check executed\n';
                report += '- Security report generated in `target/dependency-check-report.html`\n';
                report += '- Check the [Actions summary](../actions) for details\n\n';
              } else {
                report += '**⚠️ Fallback Scan Limited**:\n';
                report += '- OWASP dependency check plugin not properly configured\n';
                report += '- Manual security review recommended\n\n';
              }
              
              report += '**🔧 Recommended Actions**:\n';
              report += '1. **Enable GitHub Advanced Security**: Contact your repository administrator\n';
              report += '2. **Configure OWASP Plugin**: Add `org.owasp:dependency-check-maven` to pom.xml\n';
              report += '3. **Manual Review**: Check dependencies for known vulnerabilities\n';
              report += '4. **Regular Updates**: Keep dependencies up to date\n\n';
              
              report += '**📋 How to Enable Full Security Scanning**:\n';
              report += '- For public repositories: GitHub Advanced Security is free\n';
              report += '- For private repositories: Requires GitHub Enterprise license\n';
              report += '- Enable in: Repository Settings → Security & analysis → GitHub Advanced Security\n\n';
              
              core.setOutput('has-critical-high', 'false');
            } else {
              // Generate normal vulnerability report
              const vulnerabilities = JSON.parse('${{ steps.dependabot-scan.outputs.vulnerabilities }}');
              
              report = '🚨 **Security Vulnerability Scan Results**\n\n';
              
              // Count vulnerabilities by severity
              const severityCounts = {
                critical: 0,
                high: 0,
                medium: 0
              };
              
              vulnerabilities.forEach(vuln => {
                const severity = vuln.security_vulnerability.severity.toLowerCase();
                if (severityCounts.hasOwnProperty(severity)) {
                  severityCounts[severity]++;
                }
              });
              
              report += `**Summary**: Found ${vulnerabilities.length} vulnerabilities (`;
              const summaryParts = [];
              if (severityCounts.critical > 0) summaryParts.push(`${severityCounts.critical} Critical`);
              if (severityCounts.high > 0) summaryParts.push(`${severityCounts.high} High`);
              if (severityCounts.medium > 0) summaryParts.push(`${severityCounts.medium} Medium`);
              report += summaryParts.join(', ') + ')\n\n';
              
              // Group vulnerabilities by severity
              const groupedVulns = {
                critical: [],
                high: [],
                medium: []
              };
              
              vulnerabilities.forEach(vuln => {
                const severity = vuln.security_vulnerability.severity.toLowerCase();
                if (groupedVulns.hasOwnProperty(severity)) {
                  groupedVulns[severity].push(vuln);
                }
              });
              
              // Add Critical/High severity issues
              if (severityCounts.critical > 0 || severityCounts.high > 0) {
                report += '**🔴 Critical/High Severity Issues:**\n';
                [...groupedVulns.critical, ...groupedVulns.high].forEach(vuln => {
                  const sv = vuln.security_vulnerability;
                  const pkg = sv.package;
                  report += `- **${pkg.name}** v${vuln.dependency.package.version} - ${sv.advisory.cve_id || 'No CVE'}\n`;
                  report += `  - **Impact**: ${sv.advisory.summary}\n`;
                  report += `  - **CVSS Score**: ${sv.advisory.cvss?.score || 'N/A'}\n`;
                  report += `  - **Recommendation**: Update to version ${sv.first_patched_version?.identifier || 'latest'}\n\n`;
                });
              }
              
              // Add Medium severity issues
              if (severityCounts.medium > 0) {
                report += '**🟡 Medium Severity Issues:**\n';
                groupedVulns.medium.forEach(vuln => {
                  const sv = vuln.security_vulnerability;
                  const pkg = sv.package;
                  report += `- **${pkg.name}** v${vuln.dependency.package.version} - ${sv.advisory.cve_id || 'No CVE'}\n`;
                  report += `  - **Impact**: ${sv.advisory.summary}\n`;
                  report += `  - **CVSS Score**: ${sv.advisory.cvss?.score || 'N/A'}\n`;
                  report += `  - **Recommendation**: Update to version ${sv.first_patched_version?.identifier || 'latest'}\n\n`;
                });
              }
              
              // Add remediation steps
              report += '**🔧 Remediation Steps:**\n';
              report += '1. Update dependencies using: `mvn versions:use-latest-versions`\n';
              report += '2. Review and test changes\n';
              report += '3. Re-run security scan\n\n';
              
              core.setOutput('has-critical-high', (severityCounts.critical + severityCounts.high) > 0 ? 'true' : 'false');
            }
            
            // Add contact information (common for both scenarios)
            report += '---\n';
            report += '📞 **Need Help?** Contact your Application Security Team at security@company.com for assistance with vulnerability remediation.';
            
            core.setOutput('report', report);

      - name: 💬 Post PR Comment with Findings
        if: steps.dependabot-scan.outputs.medium-plus-vulns > 0
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const report = `${{ steps.generate-report.outputs.report }}`;
            
            // Check if there's already a comment from this workflow
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('Security Vulnerability Scan Results')
            );
            
            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: report
              });
              console.log('Updated existing PR comment');
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: report
              });
              console.log('Created new PR comment');
            }

      - name: 🚨 Set PR Status Check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scanMethod = '${{ steps.dependabot-scan.outputs.scan-method }}';
            const totalVulns = parseInt('${{ steps.dependabot-scan.outputs.medium-plus-vulns }}');
            const hasCriticalHigh = '${{ steps.generate-report.outputs.has-critical-high }}' === 'true';
            
            let state, description;
            
            if (scanMethod === 'fallback-required') {
              // Handle fallback scenario
              const hasReport = '${{ steps.maven-security-check.outputs.has-report }}' === 'true';
              if (hasReport) {
                state = 'success';
                description = '⚠️ Limited security scan completed - GitHub Advanced Security required for full analysis';
              } else {
                state = 'success';
                description = '⚠️ Basic security check completed - Consider enabling GitHub Advanced Security';
              }
            } else if (totalVulns === 0) {
              state = 'success';
              description = '✅ No medium+ severity vulnerabilities found';
            } else if (hasCriticalHigh) {
              state = 'failure';
              description = `❌ Found ${totalVulns} vulnerabilities including Critical/High severity issues`;
            } else {
              state = 'success';
              description = `⚠️ Found ${totalVulns} medium severity vulnerabilities - review recommended`;
            }
            
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: state,
              description: description,
              context: 'Security Scan / Vulnerability Check'
            });
            
            console.log(`Set PR status: ${state} - ${description}`);

      - name: 📈 Update Workflow Summary
        if: always()
        run: |
          echo "## 🔍 Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Total Vulnerabilities**: ${{ steps.dependabot-scan.outputs.total-vulns }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Medium+ Severity**: ${{ steps.dependabot-scan.outputs.medium-plus-vulns }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: $([ '${{ steps.dependabot-scan.outputs.medium-plus-vulns }}' -gt 0 ] && echo '⚠️ Vulnerabilities Found' || echo '✅ Clean')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📊 Check the PR comment for detailed vulnerability information." >> $GITHUB_STEP_SUMMARY 